build:
  environment:
    python: 3.9.0
  nodes:
    my-tests:
      dependencies:
        before:
          - "pip install --upgrade 'tox>=3.24,<4.0'"
          - "pip install --upgrade 'poetry>=1.1.4,<2.0'"
    analysis:
      tests:
        override:
          - py-scrutinizer-run
checks:
  python:
    code_rating: true
    duplicate_code: true
